src/Entity/Film.php
<?php

namespace App\Entity;

use App\Repository\FilmRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FilmRepository::class)
 */
class Film
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Titre;

    /**
     * @ORM\Column(type="integer")
     */
    private $annee_sortie;

    /**
     * @ORM\Column(type="text")
     */
    private $resume;

    
    /**
     * @ORM\Column(type="text")
     */
    private $affiche;

    /**
     * @ORM\ManyToOne(targetEntity=Genre::class, inversedBy="Films")
     * @ORM\JoinColumn(nullable=false)
     */
    private $genre;

    /**
     * @ORM\ManyToMany(targetEntity=Acteur::class, inversedBy="films")
     */
    private $acteurs;

    public function __construct()
    {
        $this->acteurs = new ArrayCollection();
    }

    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAnneeSortie(): ?int
    {
        return $this->annee_sortie;
    }

    public function setAnneeSortie(int $annee_sortie): self
    {
        $this->annee_sortie = $annee_sortie;

        return $this;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    

    public function getAffiche(): ?string
    {
        return $this->affiche;
    }

    public function setAffiche(string $affiche): self
    {
        $this->affiche = $affiche;

        return $this;
    }

    public function getGenre(): ?Genre
    {
        return $this->genre;
    }

    public function setGenre(?Genre $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    /**
     * @return Collection|Acteur[]
     */
    public function getActeurs(): Collection
    {
        return $this->acteurs;
    }

    public function addActeur(Acteur $acteur): self
    {
        if (!$this->acteurs->contains($acteur)) {
            $this->acteurs[] = $acteur;
        }

        return $this;
    }

    public function removeActeur(Acteur $acteur): self
    {
        $this->acteurs->removeElement($acteur);

        return $this;
    }


}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use App\Entity\Acteur;
use App\Entity\Film;
use App\Entity\Genre;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FilmsController extends AbstractController
{
    /**
     * @Route("/films", name="films")
     */
    public function index(): Response
    {
        $films = $this->getDoctrine()
            ->getRepository(Film::class)
            ->findALL();

        return $this->render('films/index.html.twig', [
            'controller_name' => 'FilmsController',
            'films'           => $films
        ]);
    }

     /**
     * @Route("/films/creation", name="films_create")
     */
    public function create(Request $request): Response
    {
            if($request->isMethod("POST")){
               $titre= $request->request->get('titre');
               $resume= $request->request->get('resume');
               $annee_sortie= $request->request->get('annee_sortie');
               $acteurs= $request->request->get('acteur');
               $affiche= $request->request->get('affiche');
               $genre_id= $request->request->get('genre');

               $genre = $this->getDoctrine()
               ->getRepository(Genre::class)
               ->find($genre_id);

               

                $film =  new Film;
                $film->setTitre($titre);
                $film->setResume($resume);
                $film->setAnneeSortie($annee_sortie);  
                //$film->setActeur($acteur);
                $film->setGenre($genre);
                $film->setAffiche($affiche);   
                
                foreach ($acteurs as $id){
                    $acteur = $this->getDoctrine()
                    ->getRepository(Acteur::class)
                    ->find($id);
                    $film -> addActeur($acteur);

                }
                $em = $this->getDoctrine()->getManager();
                $em->persist($film);
                $em->flush();


                return $this->redirectToRoute('films');
            

            } 
            $genres = $this->getDoctrine()
            ->getRepository(Genre::class)
            ->findALL();

            $acteurs = $this->getDoctrine()
            ->getRepository(Acteur::class)
            ->findALL();
            
            return $this->render('films/create.html.twig', [
                    'controller_name' => 'FilmsController',
                    'genres'           => $genres,
                    'acteurs' => $acteurs,
                ]);
            
    }

     /**
     * @Route("/films/{id}/edition", name="films_edit")
     */
    
    public function edit($id, Request $request): Response
    {
                $film = $this->getDoctrine()
                ->getRepository(Film::class)
                ->find($id);

                $acteurs = $this->getDoctrine()
                ->getRepository(Acteur::class)
                ->findALL();

                
                $genres = $this->getDoctrine()
                ->getRepository(Genre::class)
                ->findALL();

            
             if($request->isMethod("POST")){
                $titre= $request->request->get('titre');
                $film -> setTitre($titre);
                $acteurs = $request->request->get('acteur');

                $genres = $request->request->get('genre');

                /*

                $film ->setGenre($genres);*/

                $film->getActeurs()->clear();
                

                foreach ($acteurs as $id){
                    $acteur = $this->getDoctrine()
                    ->getRepository(Acteur::class)
                    ->find($id);
                    $film -> addActeur($acteur);

                }

                /*foreach ($genres as $id){
                    $genre = $this->getDoctrine()
                    ->getRepository(Genre::class)
                    ->find($id);
                    $film -> setGenre($genre);

                }
                
                $film->getGenre()->clear();*/

                $em = $this->getDoctrine()->getManager();     
                $em->flush();

                return $this->redirectToRoute('films');
            
            } 
            
            return $this->render('films/edit.html.twig', [
                    'controller_name' => 'FilmsController',
                    'film' => $film,
                    'acteurs' => $acteurs,
                    'genres' => $genres,
                ]);
            
    }






    /**
     * @Route("/films/{id}/suppression", name="films_delete")
     */
    
    public function delete($id, Request $request): Response
    {
                $film = $this->getDoctrine()
                ->getRepository(Film::class)
                ->find($id);
            

                $em = $this->getDoctrine()->getManager();  
                $em->remove($film);
                $em->flush();


                return $this->redirectToRoute('films');
            
             
            
    }




}

templates/films/create.html.twig
 {% extends 'base.html.twig' %}

 {% block title %}Liste des films{% endblock %}

 {% block body %}



<form method="POST">

    <p>
        <label for="titre">
            Titre
        </label>
        <input type="text" name="titre" id="titre" />
    </p>
    <p>
        <label for="resume">
            Résumé
        </label>
        <textarea name="resume" id="resume"></textarea>
    </p>
    <p>
        <label for="annee_sortie">
            Année de sortie 
        </label>
        <input type="number" min="1900" max="2021" step="1" name ="annee_sortie" id="annee_sortie" />
    </p>
    <p>
        <label for="acteur">
            Acteur
        </label>
        <select name="acteur[]" id="acteur" multiple>
            {% for acteur in acteurs %}
            <option value="{{acteur.id}}">
            {{acteur.nom}}
            {{acteur.prenom}}
            </option>
        
    {% endfor %}
        </select>
    </p>
    <p>
        <label for="genre">
            Genre
        </label>
        <select name="genre" id="genre">
            {% for genre in genres %}
            <option value="{{genre.id}}">
            {{genre.name}}
            </option>
        
    {% endfor %}
        </select>

    </p>
    <p>
        <label for="affiche">
            Affiche
        </label>
        <textarea name="affiche" id="affiche"></textarea>
    </p>

    <p>
        <button type="submit">
            Enregistrer
        </button>
    </p>

</form>
{% endblock %}

templates/films/edit.html.twig
{% extends 'base.html.twig' %}

 {% block title %}Edition du film #{{film.id}}{% endblock %}

 {% block body %}

<form method="POST">

    <p>
        <label for="genre">
            Titre du film
        </label>
        <input type="text" name="titre" id="name" value="{{film.genre.name}}" />
    </p>

   <p>
        <label for="acteur">
            Acteur
        </label>
        <select name="acteur[]" id="acteur" multiple>
            {% for acteur in acteurs %}
            <option value="{{acteur.id}}"
                {% if film.acteurs.contains(acteur) %}
                    selected
                {% endif %}
            >
            {{acteur.nom}}
            {{acteur.prenom}}
            </option>
        
    {% endfor %}
        </select>
    </p>


    <p>
        <label for="genre">
            Genre
        </label>
        <select name="genre" id="genre">
            {% for genre in genres %}
            <option value="{{genre.id}}">
            {{genre.name}}
            </option>
        
    {% endfor %}
        </select>

    </p>
   

    <p>
        <button type="submit">
            Enregistrer
        </button>
    </p>

</form>

{% endblock %}

templates/films/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmsController!{% endblock %}

{% block body %}

<a href="{{ url('films_create') }}">Nouveau Film</a>

<div>
    {% for film in films %}
        <h2>#{{ film.id }} : {{ film.titre }}</h2>
        <h3>Sortie : {{ film.anneeSortie }}</h3>
            <p>Résumé : {{ film.resume }}</p>
            {% for acteur in film.acteurs %}
                <p>Acteur : {{acteur.nom}} {{acteur.prenom}}</p>
            {% endfor %}
        {% if film.genre is not null %}
            <p>Genre : {{ film.genre.name }}</p>
        {% endif %}
            <p>Affiche : {{film.affiche}}</p>
        <hr />
        <a href="{{ url('films_edit', {'id' : film.id }) }}">Editer</a>
        <hr/>
        <a href="{{ url('films_delete', {'id' : film.id }) }}">Supprimer</a>

    {% endfor %}
</div>

{% endblock %}




{#{% extends 'base.html.twig' %}

{% block title %}Hello FilmsController!{% endblock %}

{% block body %}

<a href="{{ url('genres_create') }}">Nouveau genre</a>

<div>
    {% for genre in genres %}
        <h2>#{{ genre.id }} : {{ genre.name }}</h2>
        <a href="{{ url('genres_edit', {'id' : genre.id }) }}">Editer</a>
        {% if genre.films|length == 0 %}
        <br/>
        <a href="{{ url('genres_delete', {'id' : genre.id }) }}">Supprimer</a>
        {% endif %}
        
        
        {% endfor %}
</div>

{% endblock %}#}